//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VocabModel", "FK__WORDS__LANGUAGE___0519C6AF", "LANGUAGES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VX.Domain.EntityLanguage), "WORDS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VX.Domain.EntityWord), true)]

#endregion

namespace VX.Domain
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VXEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VXEntities object using the connection string found in the 'VXEntities' section of the application configuration file.
        /// </summary>
        public VXEntities() : base("name=VXEntities", "VXEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VXEntities object.
        /// </summary>
        public VXEntities(string connectionString) : base(connectionString, "VXEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VXEntities object.
        /// </summary>
        public VXEntities(EntityConnection connection) : base(connection, "VXEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityLanguage> EntityLanguages
        {
            get
            {
                if ((_EntityLanguages == null))
                {
                    _EntityLanguages = base.CreateObjectSet<EntityLanguage>("EntityLanguages");
                }
                return _EntityLanguages;
            }
        }
        private ObjectSet<EntityLanguage> _EntityLanguages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityWord> EntityWords
        {
            get
            {
                if ((_EntityWords == null))
                {
                    _EntityWords = base.CreateObjectSet<EntityWord>("EntityWords");
                }
                return _EntityWords;
            }
        }
        private ObjectSet<EntityWord> _EntityWords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntityLanguages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntityLanguages(EntityLanguage entityLanguage)
        {
            base.AddObject("EntityLanguages", entityLanguage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntityWords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntityWords(EntityWord entityWord)
        {
            base.AddObject("EntityWords", entityWord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VocabModel", Name="EntityLanguage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityLanguage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityLanguage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static EntityLanguage CreateEntityLanguage(global::System.Int32 id)
        {
            EntityLanguage entityLanguage = new EntityLanguage();
            entityLanguage.Id = id;
            return entityLanguage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Abbreviation
        {
            get
            {
                return _Abbreviation;
            }
            set
            {
                OnAbbreviationChanging(value);
                ReportPropertyChanging("Abbreviation");
                _Abbreviation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Abbreviation");
                OnAbbreviationChanged();
            }
        }
        private global::System.String _Abbreviation;
        partial void OnAbbreviationChanging(global::System.String value);
        partial void OnAbbreviationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VocabModel", "FK__WORDS__LANGUAGE___0519C6AF", "WORDS")]
        public EntityCollection<EntityWord> Words
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityWord>("VocabModel.FK__WORDS__LANGUAGE___0519C6AF", "WORDS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityWord>("VocabModel.FK__WORDS__LANGUAGE___0519C6AF", "WORDS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VocabModel", Name="EntityWord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityWord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityWord object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static EntityWord CreateEntityWord(global::System.Int32 id)
        {
            EntityWord entityWord = new EntityWord();
            entityWord.Id = id;
            return entityWord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Spelling
        {
            get
            {
                return _Spelling;
            }
            set
            {
                OnSpellingChanging(value);
                ReportPropertyChanging("Spelling");
                _Spelling = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Spelling");
                OnSpellingChanged();
            }
        }
        private global::System.String _Spelling;
        partial void OnSpellingChanging(global::System.String value);
        partial void OnSpellingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transcription
        {
            get
            {
                return _Transcription;
            }
            set
            {
                OnTranscriptionChanging(value);
                ReportPropertyChanging("Transcription");
                _Transcription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transcription");
                OnTranscriptionChanged();
            }
        }
        private global::System.String _Transcription;
        partial void OnTranscriptionChanging(global::System.String value);
        partial void OnTranscriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LanguageId;
        partial void OnLanguageIdChanging(Nullable<global::System.Int32> value);
        partial void OnLanguageIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VocabModel", "FK__WORDS__LANGUAGE___0519C6AF", "LANGUAGES")]
        public EntityLanguage Languages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityLanguage>("VocabModel.FK__WORDS__LANGUAGE___0519C6AF", "LANGUAGES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityLanguage>("VocabModel.FK__WORDS__LANGUAGE___0519C6AF", "LANGUAGES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityLanguage> LanguagesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityLanguage>("VocabModel.FK__WORDS__LANGUAGE___0519C6AF", "LANGUAGES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityLanguage>("VocabModel.FK__WORDS__LANGUAGE___0519C6AF", "LANGUAGES", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
